name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt || true
          pip install pytest flake8

      - name: Lint (Python)
        run: flake8 .

      - name: Test (Python)
        run: pytest -q

      - name: Lint (JS/TS)
        run: |
          npm install --legacy-peer-deps || true
          npx eslint . --ext .js,.ts,.tsx || true

      - name: Check Docs Updated
        run: |
          git fetch origin main
          if ! git diff --name-only origin/main | grep -q -E 'README.md|CHANGELOG.md'; then
            echo "❌ Docs not updated. Update README/CHANGELOG."
            exit 1
          fi
