name: Autofix Browser Errors (Playwright MCP)
on:
  # This trigger allows the workflow to be manually triggered from the Actions tab.
  workflow_dispatch:
    inputs:
      url:
        description: The local dev URL to check (e.g. http://localhost:3000)
        required: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Check Playwright MCP
        run: |
          if ! pnpm dlx @playwright/mcp@latest --version > /dev/null 2>&1; then
            pnpm dlx @playwright/mcp@latest --help
          fi
          pnpm dlx @playwright/mcp@latest --help

      - name: Start Autofix Loop
        # This action runs the autofix loop for browser errors using Playwright MCP.
        # Ensure the action is defined in ./.github/actions/autofix-loop or link to its documentation.
        uses: ./.github/actions/autofix-loop
        with:
          url: ${{ inputs.url }}
          playwright_mcp: pnpm dlx @playwright/mcp@latest
          playwright_mcp_args: --browser=chromium --headless --no-sandbox --disable-web-security --disable-gpu --disable-dev-shm-usage  
          playwright_mcp_timeout: 60000
          default_wait_time: 30000
          playwright_mcp_max_wait: 30000
          playwright_mcp_max_wait_for_navigation: 30000
          playwright_mcp_max_wait_for_event: 30000
          playwright_mcp_max_wait_for_selector: 30000
          playwright_mcp_max_wait_for_load_state: 30000
          playwright_mcp_max_wait_for_function: 30000
          playwright_mcp_max_wait_for_request: 30000
          playwright_mcp_max_wait_for_response: 30000
          playwright_mcp_max_wait_for_timeout: 30000
          playwright_mcp_max_wait_for_element_state: 30000
          playwright_mcp_max_wait_for_element_count: 30000
          playwright_mcp_max_wait_for_element_state: ${{ default_wait_time }}
          playwright_mcp_max_wait_for_element_count: ${{ default_wait_time }}
          playwright_mcp_max_wait_for_function: 30000
          playwright_mcp_max_wait_for_request: 30000 
          playwright_mcp_max_wait_for_response: 30000
          playwright_mcp_max_wait_for_timeout: 30000
          playwright_mcp_max_wait_for_element_state: 30000
          playwright_mcp_max_wait_for_element_count: 30000
          playwright_mcp_max_wait_for_element_text: 30000
          playwright_mcp_max_wait_for_element_value: 30000
          playwright_mcp_max_wait_for_element_attribute: 30000
          playwright_mcp_max_wait_for_element_property: 30000